import { Product, StoreConfig } from './types';

export const STORE_CONFIG: StoreConfig = {
  name: "Distribuidora de Vasos & Termos",
  logoText: "VT",
  whatsappNumber: "5491112345678", // Reemplazar con tu número real
  currencySymbol: "$",
  minOrderAmount: 20000, // Ajustado a un valor razonable según los precios
  openHours: "Lun-Vie: 9:00 - 18:00 | Sáb: 9:00 - 13:00",
  adminPin: "1234",
};

// Helper para generar placeholders
const getPlaceholder = (text: string) => `https://placehold.co/400x400/f1f5f9/334155?text=${encodeURIComponent(text)}`;

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'v1',
    name: "Vasos Flip 900 ML",
    description: "Hechos en doble capa de acero inoxidable. Aptos para bebidas frías y calientes. Sorbete interno para usarlo como botella. Precio Caja (30u): $14,900 c/u.",
    priceRetail: 16900,
    priceWholesale: 14900,
    wholesaleThreshold: 10,
    category: "Vasos Térmicos",
    imageUrl: getPlaceholder("Vaso Flip 900ML"),
    stock: 100,
  },
  {
    id: 'v2',
    name: "Vasos Quencher Batik 1.2 Litros",
    description: "Tapón para sorbete + base de silicona. Doble capa acero inox. Aptos frío/calor. Precio Caja (36u): $16,000 c/u.",
    priceRetail: 18900,
    priceWholesale: 16000,
    wholesaleThreshold: 10,
    category: "Línea Quencher",
    imageUrl: getPlaceholder("Quencher Batik"),
    stock: 50,
  },
  {
    id: 'v3',
    name: "Vasos Diseño Sanrio 1.2 Litros",
    description: "ÚLTIMOS EN STOCK. Doble capa acero inox, sorbete acero, media manija. Pueden elegir diseños pero no repetir cantidad.",
    priceRetail: 17900,
    priceWholesale: 15900,
    wholesaleThreshold: 10,
    category: "Infantil / Kawaii",
    imageUrl: getPlaceholder("Diseño Sanrio"),
    stock: 15,
  },
  {
    id: 'v4',
    name: "Vasos Quencher 1.2L + Base Silicona",
    description: "Doble capa acero inox, tapa hermética, sorbete plástico. Agarre acabado silicona. Precio Caja (36u): $14,990.",
    priceRetail: 17900,
    priceWholesale: 14990,
    wholesaleThreshold: 10,
    category: "Línea Quencher",
    imageUrl: getPlaceholder("Quencher Base Silicona"),
    stock: 80,
  },
  {
    id: 'v5',
    name: "Vasos Quencher Flower 1.2 Litros",
    description: "Diseño floral exclusivo. Doble capa térmica.",
    priceRetail: 17900,
    priceWholesale: 16000, // Estimado
    wholesaleThreshold: 10,
    category: "Línea Quencher",
    imageUrl: getPlaceholder("Quencher Flower"),
    stock: 40,
  },
  {
    id: 'v6',
    name: "Vasos Térmicos con Manija Rotativa",
    description: "Sistema de agarre ergonómico y rotativo. Mantiene temperatura por horas.",
    priceRetail: 17900,
    priceWholesale: 16000, // Estimado
    wholesaleThreshold: 10,
    category: "Vasos Térmicos",
    imageUrl: getPlaceholder("Manija Rotativa"),
    stock: 60,
  },
  {
    id: 'v7',
    name: "Vasos Térmicos 500 ML Clásicos",
    description: "Ideal oficina o viaje corto. Tamaño compacto.",
    priceRetail: 14900,
    priceWholesale: 13000, // Estimado
    wholesaleThreshold: 10,
    category: "Vasos Térmicos",
    imageUrl: getPlaceholder("Vaso 500ML Clásico"),
    stock: 100,
  },
  {
    id: 'v8',
    name: "Vasos Kawaii 1 Litro",
    description: "Diseños tiernos y coloridos. Gran capacidad.",
    priceRetail: 16900,
    priceWholesale: 15000,
    wholesaleThreshold: 10,
    category: "Infantil / Kawaii",
    imageUrl: getPlaceholder("Vaso Kawaii 1L"),
    stock: 30,
  },
  {
    id: 'v9',
    name: "Vasos Kawaii Gatitos 1 Litro",
    description: "Edición especial Cat Lovers.",
    priceRetail: 16900,
    priceWholesale: 15000,
    wholesaleThreshold: 10,
    category: "Infantil / Kawaii",
    imageUrl: getPlaceholder("Kawaii Gatitos"),
    stock: 30,
  },
  {
    id: 'v10',
    name: "Vasos Tumblr Antiderrame 1.2L",
    description: "Tapa 100% antiderrame. Doble capa acero inox. Precio Caja (36u): $15,900 c/u.",
    priceRetail: 18900,
    priceWholesale: 15900,
    wholesaleThreshold: 10,
    category: "Vasos Térmicos",
    imageUrl: getPlaceholder("Tumblr Antiderrame"),
    stock: 55,
  },
  {
    id: 'v11',
    name: "Vasos Térmicos 1.2 Litros (Liso)",
    description: "Precio Caja (30u): $15,500 c/u. Colores lisos.",
    priceRetail: 18900,
    priceWholesale: 15500,
    wholesaleThreshold: 10,
    category: "Vasos Térmicos",
    imageUrl: getPlaceholder("Vaso Liso 1.2L"),
    stock: 40,
  },
  {
    id: 'v12',
    name: "Vaso con Parlante 500 ML",
    description: "Con destapador y parlante en base (desmontable) carga USB. Precio Caja (30u): $15,900 c/u.",
    priceRetail: 18500,
    priceWholesale: 15900,
    wholesaleThreshold: 10,
    category: "Tecnología y Hogar",
    imageUrl: getPlaceholder("Vaso Parlante"),
    stock: 20,
  },
  {
    id: 'v13',
    name: "Vasos Take Away 500 ML",
    description: "Precio Caja (30u): $14,500 c/u. Estilo café para llevar.",
    priceRetail: 16900,
    priceWholesale: 14500,
    wholesaleThreshold: 10,
    category: "Vasos Térmicos",
    imageUrl: getPlaceholder("Take Away 500ML"),
    stock: 60,
  },
  {
    id: 'v14',
    name: "Quencher Flower 1.2L (Variante)",
    description: "Tapón sorbete + base silicona. Precio Caja (36u): $16,900 c/u.",
    priceRetail: 18900,
    priceWholesale: 16900,
    wholesaleThreshold: 10,
    category: "Línea Quencher",
    imageUrl: getPlaceholder("Quencher Flower Var"),
    stock: 35,
  },
  {
    id: 'v15',
    name: "Vasos Térmicos Animal Print 1.2L",
    description: "Diseño Animal Print. Tapón sorbete + base silicona. Precio Caja (36u): $16,500.",
    priceRetail: 18900,
    priceWholesale: 16500,
    wholesaleThreshold: 10,
    category: "Línea Quencher",
    imageUrl: getPlaceholder("Animal Print 1.2L"),
    stock: 25,
  },
  {
    id: 'v16',
    name: "Vasos Dupe 1.2 Litros",
    description: "Sorbete de acero inoxidable. Herméticos. Precio Caja (36u): $14,900 c/u.",
    priceRetail: 17900,
    priceWholesale: 14900,
    wholesaleThreshold: 10,
    category: "Línea Quencher",
    imageUrl: getPlaceholder("Dupe 1.2L"),
    stock: 45,
  },
  {
    id: 'v17',
    name: "Vasos Quencher 1.2L (Estándar)",
    description: "Sorbete plástico, tapa hermética. Precio Caja (36u): $14,500.",
    priceRetail: 17900,
    priceWholesale: 14500,
    wholesaleThreshold: 10,
    category: "Línea Quencher",
    imageUrl: getPlaceholder("Quencher Estándar"),
    stock: 70,
  },
  {
    id: 'v18',
    name: "Vasos Térmicos Sin Manija 650 ML",
    description: "Sorbete plástico y cierre hermético. Precio Caja (30u): $12,500 c/u.",
    priceRetail: 15900,
    priceWholesale: 12500,
    wholesaleThreshold: 10,
    category: "Vasos Térmicos",
    imageUrl: getPlaceholder("Vaso Sin Manija"),
    stock: 40,
  },
  {
    id: 'v19',
    name: "Set de Vasos x3",
    description: "Plástico rígido, libres de BPA. Precio Caja (30u): $12,900 cada set.",
    priceRetail: 15900,
    priceWholesale: 12900,
    wholesaleThreshold: 10,
    category: "Sets y Combos",
    imageUrl: getPlaceholder("Set x3"),
    stock: 30,
  },
  {
    id: 'v20',
    name: "Vasos Térmicos con Destapador",
    description: "Incluye destapador en su tapa. Precio Caja (30u): $10,900 c/u.",
    priceRetail: 13900,
    priceWholesale: 10900,
    wholesaleThreshold: 10,
    category: "Vasos Térmicos",
    imageUrl: getPlaceholder("Vaso Destapador"),
    stock: 35,
  },
  {
    id: 'v21',
    name: "Vasos Térmicos 500 ML (Económico)",
    description: "Precio Caja (36u): $11,900 c/u.",
    priceRetail: 14900,
    priceWholesale: 11900,
    wholesaleThreshold: 10,
    category: "Vasos Térmicos",
    imageUrl: getPlaceholder("Vaso 500ML Eco"),
    stock: 60,
  },
  {
    id: 'v22',
    name: "Vasos Térmicos 500 ML Modelos Varios",
    description: "Precio Caja (40u): $11,900 c/u.",
    priceRetail: 15900,
    priceWholesale: 11900,
    wholesaleThreshold: 10,
    category: "Vasos Térmicos",
    imageUrl: getPlaceholder("Vaso 500ML Varios"),
    stock: 50,
  },
  {
    id: 'v23',
    name: "Vasos Térmicos Doble Tapa 800 ML",
    description: "Precio Caja (30u): $9,900 c/u.",
    priceRetail: 12500,
    priceWholesale: 9900,
    wholesaleThreshold: 10,
    category: "Vasos Térmicos",
    imageUrl: getPlaceholder("Doble Tapa 800ML"),
    stock: 40,
  },
  {
    id: 'v24',
    name: "Vasos Térmicos Labubu 550 ML",
    description: "Diseño Labubu.",
    priceRetail: 11900,
    priceWholesale: 10500, // Estimado
    wholesaleThreshold: 10,
    category: "Infantil / Kawaii",
    imageUrl: getPlaceholder("Labubu 550ML"),
    stock: 20,
  },
  {
    id: 'v25',
    name: "Vasos Quencher Labubu 1.2 Litros",
    description: "Gran capacidad con diseño Labubu.",
    priceRetail: 16900,
    priceWholesale: 14900, // Estimado
    wholesaleThreshold: 10,
    category: "Infantil / Kawaii",
    imageUrl: getPlaceholder("Labubu 1.2L"),
    stock: 15,
  },
  {
    id: 'v26',
    name: "Vasos Térmicos Labubu 500 ML",
    description: "Mediano.",
    priceRetail: 14900,
    priceWholesale: 12900, // Estimado
    wholesaleThreshold: 10,
    category: "Infantil / Kawaii",
    imageUrl: getPlaceholder("Labubu 500ML"),
    stock: 25,
  },
  {
    id: 'v27',
    name: "Vasos Quencher Importados 1.2L",
    description: "Calidad Premium Importada.",
    priceRetail: 45900,
    priceWholesale: 41000, // Estimado
    wholesaleThreshold: 10,
    category: "Línea Premium",
    imageUrl: getPlaceholder("Quencher Importado"),
    stock: 10,
  },
  {
    id: 'v28',
    name: "Vasos Hello Kitty Importados",
    description: "Edición especial coleccionable.",
    priceRetail: 65000,
    priceWholesale: 58000, // Estimado
    wholesaleThreshold: 5, // Umbral más bajo por ser caro
    category: "Línea Premium",
    imageUrl: getPlaceholder("Hello Kitty"),
    stock: 5,
  },
  {
    id: 'v29',
    name: "Vaso Térmico 500 ML con Sensor Temp",
    description: "Muestra la temperatura en la tapa. Precio Caja (30u): $13,000 c/u.",
    priceRetail: 15900,
    priceWholesale: 13000,
    wholesaleThreshold: 10,
    category: "Tecnología y Hogar",
    imageUrl: getPlaceholder("Sensor Temp"),
    stock: 30,
  },
  {
    id: 'v30',
    name: "Vasos Térmicos 500 ML con Filtro",
    description: "Con filtro para infusiones. Precio Caja (36u): $13,900 c/u.",
    priceRetail: 16900,
    priceWholesale: 13900,
    wholesaleThreshold: 10,
    category: "Vasos Térmicos",
    imageUrl: getPlaceholder("Vaso Filtro"),
    stock: 45,
  }
];

export const CATEGORIES = Array.from(new Set(MOCK_PRODUCTS.map(p => p.category)));